language: python
matrix:
  include:
    - install:
      - git clone https://github.com/edx/devstack.git
      - (cd devstack; make dev.provision)
      - (cd devstack; make dev.up)
      script: echo TODO
      services:
        - docker
      env:
        name: Integration
    - install:
      - pip install tox
      script: tox -e django18
      env:
        name: Django 1.8
    - install:
      - pip install tox
      script: tox -e django111
      env:
        name: Django 1.11
