coverage:
  status:
    project:
      default:
        enabled: yes
        target: 50%
    patch:
      default:
        enabled: yes
  ignore:
    - "edx_sga/tests/integration_tests.py"
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
