coverage:
  status:
    project:
      default:
        enabled: yes
        target: 50%
    patch:
      default:
        enabled: yes
        target: 50%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
