name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches:
    - '**'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  python-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.8']
        toxenv: [py38-django32]

    steps:
      - uses: actions/checkout@v3

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: tox install
        run: pip install tox

      - name: Run Tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox

      - name: Upload coverage to CodeCov
        if: matrix.python-version == '3.8' && matrix.toxenv == 'py38-django32'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
